### ISSUE TITLE
Action giving zero hits for macOS Xcode Swift project

### ISSUE THREAD

**Issue by grzegorzkrukowski** [mikehardy/buildcache-action#57]
I am trying to integrate this action into my workflow:

```
jobs:
  build:
    name: Build
    runs-on: macos-11
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Xcode
        uses: my_company/github-actions/setup-xcode@master
      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v1
        continue-on-error: true
        with:
          upload_buildcache_log: "true"
      - name: Install SwiftLint
        run: |
          rm -f '/usr/local/bin/swiftlint'
          brew reinstall swiftlint
      - name: Lint Swift source files
        run: |
          swiftlint lint --strict --quiet
      - name: Install XcodeGen
        run: |
          brew install xcodegen
      - name: Cache SPM dependencies
        uses: actions/cache@v2
        with:
          path: |
            .buildSPM
          key: ${{ runner.os }}-spm-${{ hashFiles('MyProject.xcodeproj/**/Package.resolved') }}
          # Fallback key if Package.resolved cannot be found (since we regenerate the project)
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Generate Xcode project
        run: |
          xcodegen generate
      - name: Install xcpretty
        run: |
          gem install xcpretty
      - name: Build
        # Specify clonedSourcePackagesDirPath for SPM caching to work
        run: |
          xcodebuild CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ -derivedDataPath build -UseModernBuildSystem=YES -project MyProject.xcodeproj -clonedSourcePackagesDirPath .buildSPM -scheme MainScheme CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO OTHER_CFLAGS="-Wno-ambiguous-macro" build -quiet
```

The project is written in Swift with SPM and it's macOS project. 

It only shows hits on some dependencies:
```
build/Build/Intermediates.noindex/Sentry.build
```

I cannot make it work. Should it work or macOS is not supported?
